# Generated by Django 4.0.5 on 2023-03-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0004_alter_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
